### ISSUE TITLE
Cannot find implementation for getStringFromNative()

### ISSUE THREAD

**Issue by mongoose54** [quanhua92/NDK_OpenCV_AndroidStudio#1]
@quanhua92 I am not sure what I am doing wrong. Any help would be so much appreciated. I followed your tutorial step-by-step but I am getting this annoying error:

```
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime: Process: com.example.alex.myapplication, PID: 8428
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.example.alex.myapplication.NativeClass.getStringFromNative() (tried Java_com_example_alex_myapplication_NativeClass_getStringFromNative and Java_com_example_alex_myapplication_NativeClass_getStringFromNative__)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at com.example.alex.myapplication.NativeClass.getStringFromNative(Native Method)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at com.example.alex.myapplication.MainActivity.onCreate(MainActivity.java:20)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5990)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5257)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-27 15:56:02.523 8428-8428/com.example.alex.myapplication E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

Here is my `com_example_alex_myapplication_NativeClass.h`:

```
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_alex_myapplication_NativeClass */

#ifndef _Included_com_example_alex_myapplication_NativeClass
#define _Included_com_example_alex_myapplication_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_alex_myapplication_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alex_myapplication_NativeClass_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
```

Here is my `com_example_alex_myapplication_NativeClass.cpp`:

```
#include "com_example_alex_myapplication_NativeClass.h"

JNIEXPORT jstring JNICALL Java_com_example_alex_myapplication_NativeClass_getStringFromNative
        (JNIEnv * env, jobject obj){
    return env->NewStringUTF("Hello from JNI");
}

```

And here is my  `MainActivity.java`

```
package com.example.alex.myapplication;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {

    static {
        System.loadLibrary("MyLib");
        System.loadLibrary("opencv_java3");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        TextView tv = (TextView) findViewById(R.id.testTextView);
        tv.setText(NativeClass.getStringFromNative());
    }
}

```

**Comment by quanhua92** [comment]
Hi, I think that you forgot to call "System.loadLibrary"

**Comment by quanhua92** [comment]
Sorry. You have already called System. LoadLibrary. I find that the function in your .h and .cpp are not identical. Please check the 2nd parameter. In .h it is jclass but in .cpp it is jobject
